# Generated by Django 4.2.16 on 2024-12-01 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shoper', '0013_alter_buyerform_contact_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paypage',
            name='user',
        ),
    ]
