# Generated by Django 4.2.16 on 2025-01-09 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shoper', '0015_remove_buyerform_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='entertainmentpages',
            name='user',
        ),
        migrations.RemoveField(
            model_name='fashionpages',
            name='user',
        ),
        migrations.RemoveField(
            model_name='healthproductspages',
            name='user',
        ),
        migrations.RemoveField(
            model_name='homedecorpages',
            name='user',
        ),
        migrations.RemoveField(
            model_name='industrialproductspages',
            name='user',
        ),
        migrations.RemoveField(
            model_name='kidstoyspages',
            name='user',
        ),
        migrations.RemoveField(
            model_name='luggagebagspages',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sellerpages',
            name='user',
        ),
        migrations.RemoveField(
            model_name='shoespages',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sportspages',
            name='user',
        ),
        migrations.RemoveField(
            model_name='watchjewelrypages',
            name='user',
        ),
    ]
